site_name: Robot Developer Extensions for Creating ROS 2 Packages
repo_url: https://github.com/ranch-hand-robotics/rde-ros-template
edit_uri: edit/master/docs/
nav:
  - Home: index.md
  - User Guide:
      - Getting Started: index.md
      - C++ ROS 2 Node: cpp-node.md
      - Python ROS 2 Node: python-node.md
      - Node.js ROS 2 Node: nodejs-node.md
      - Resource Package: resource-package.md
  - Contributing: ../CONTRIBUTING.md

theme: 
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
use_directory_urls: false
strict: true
