site_name: Robot Developer Extensions for Creating ROS 2 Packages
repo_url: https://github.com/ranch-hand-robotics/rde-creator
edit_uri: edit/master/docs/
nav:
  - Getting Started: index.md
  - C++ ROS 2 Package: cpp-package.md
      - Python ROS 2 Package: python-package.md
      - Node.js ROS 2 Package: nodejs-package.md
      - Resource Package: resource-package.md
      - Troubleshooting: troubleshooting.md
  - Contributing: CONTRIBUTING.md

theme: 
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
use_directory_urls: false
strict: true
